apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: syedazherali/java-student:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://localhost:3306/student_db?useSSL=false&serverTimezone=UTC"
        - name: SPRING_DATASOURCE_USERNAME
          value: "student_user"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "student_pwd"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: my-app
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: backend
