apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "p@ssw0rd"
        - name: MYSQL_DATABASE
          value: "student_db"
        - name: MYSQL_USER
          value: "student_user"
        - name: MYSQL_PASSWORD
          value: "student_pwd"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: my-app
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql

